apiVersion: v1
kind: Pod
metadata:
  name: tool-pod-airbnb
spec:
  containers:
  - name: tool-pod-airbnb
    image: debian
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: /volume/output
      name: output-volume
  volumes:
  - name: output-volume
    persistentVolumeClaim:
      claimName: pvc-airbnb
  restartPolicy: Never
